### PR TITLE
cert-manager graduation proposal

### PR DESCRIPTION
**Pull request by SgtCoDFish**
This PR is for collaboration on the proposal among the maintainer team before we submit the "official" proposal.

### CODE REVIEW

**Comment by maelvls** [comment]
The application you drafted is great. I think we shouldn't wait to opening the PR in cncf/toc. Cilium had opened [their application](https://github.com/cncf/toc/pull/952/files) before the end of their security audit, so I think we can go with it right away! That should help get eyes from the TOC.

**Review by wallrj — APPROVED** [review]
/lgtm

**Comment by SgtCoDFish** [comment]
This has been reviewed now so I'll close this and raise upstream!

**Comment by maelvls** [comment]
For anyone looking at this, the actual proposal is at https://github.com/cncf/toc/issues/1306.

**Pull request closed without merging**
